---
apiVersion: v1
kind: Service
metadata:
  name: movierental
  labels:
    app: movierental
spec:
  type: NodePort
  selector:
    app: movierental
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: movierental
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: movierental
    spec:
      containers:
      - name: movierental-c
        image: ovidiud/movierental:0.0.2-SNAPSHOT
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /movies
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
